### ISSUE TITLE
Interacting with the menu with the mouse doesn't work properly with wayland

### ISSUE THREAD

**Issue by pizzadude** [flathub/io.jor.bugdom2#2]
Interacting with the menu with the mouse doesn't work properly with wayland. When hovering over menu items, the clickable areas are in different places than the actual menu items. Removing the wayland socket via flatseal and forcing Bugdom 2 to be run with Xwayland fixes this. This is on Fedora 38 KDE.

**Comment by jorio** [comment]
I'm unable to reproduce this on my setup. Are you using DPI scaling?

Can you also paste a screenshot of the gray text at the bottom of the help screen within the game?

**Comment by jorio** [comment]
OK, I did repro this issue with another graphics driver. (Still interested in what the gray text at the bottom of the help screen reports for you, though.)

Please try this one?
`flatpak install https://dl.flathub.org/build-repo/56261/io.jor.bugdom2.flatpakref`

**Comment by pizzadude** [comment]
Hi, that build fixes it. Thanks :)
Here's the gray text at the bottom of the help screen:
![image](https://github.com/flathub/io.jor.bugdom2/assets/1454420/68df1b38-4abe-4871-b8e9-6da0da9138d5)

**Comment by jorio** [comment]
Thanks!
